[package]
name = "lipl-repo"
version = "0.1.1"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2018"

[dependencies]
warp = "0.2"
parking_lot = "0.11"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
lipl-data-disk = { path = "../lipl-data-disk" }
