[workspace]

members = [
    "lipl-axum",
    "lipl-axum-inmemorydb",
    "lipl-axum-postgres",
    "lipl-repo-http-server",
    "lipl-fs-repo",
    "lipl-postgres-repo",
    "lipl-core",
    "lipl-upload",
    "parts",
    "rest-api-client",
    "timeit",
]

[profile.release]
lto = true
strip = true
opt-level = "z"
