[workspace]

members = [
    "lipl-repo-http-server",
    "lipl-fs-repo",
    "lipl-postgres-repo",
    "lipl-types",
    "lipl-upload",
    "parts",
    "rest-api-client",
]

[profile.release]
lto = true
strip = true
opt-level = "z"
