[package]
name = "lipl-repo"
version = "0.1.1"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2018"

[dependencies]
warp = "0.2"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
lipl-io = { path = "../lipl-io" }
