[package]
name = "lipl-io"
version = "0.1.0"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
bs58 = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
uuid = "0.8"

[dev-dependencies]
tokio = { version = "0.3", features = ["macros", "rt"] }
