[workspace]

members = [
    "lipl-repo-http-server",
#    "lipl-io",
    "lipl-fs-repo",
    "lipl-postgres-repo",
    "lipl-types",
    "parts",
]

[profile.release]
lto = true
strip = true
opt-level = "z"
