[package]
name = "lipl-repo"
version = "0.1.1"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2018"

[dependencies]
warp = "0.2"
tokio = { version = "0.2", features = ["macros", "rt-core", "signal", "sync"] }
lipl-io = { path = "../lipl-io" }
log = "0.4"
env_logger = "0.8"
anyhow = "1.0"
clap = { version = "3.0.0-beta.2", features = ["derive"] }
