[package]
name = "lipl-io"
version = "0.1.7"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
thiserror = "1.0"
uuid = { version = "0.8", features = ["v4"] }
zip = "0.5"

[dev-dependencies]
clap = { version = "3.0.0-beta.2", features = ["derive"] }
