[package]
name = "lipl-core"
version = "0.1.0"
edition = "2021"

[features]
# default = ["file", "postgres"]
postgres = ["dep:deadpool-postgres", "dep:tokio-postgres"]
file = ["dep:tokio"]

[dependencies]
anyhow = { version = "1.0.59", features = ["std"] }
async-trait = "0.1"
bincode = "1"
bs58 = "0.4"
deadpool-postgres = { version = "0.10", optional = true }
etag = "4"
futures = "0.3"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_with = "2.0"
thiserror = "1"
timeit = { path = "../timeit" }
tokio = { version = "1.23", features = ["rt"], optional = true }
tokio-postgres = { version = "0.7", optional = true }
uuid = { version = "1.0", features = ["v4"] }
