[package]
name = "lipl-core"
version = "0.1.0"
edition = "2021"

[features]
postgres = ["dep:bb8-postgres"]
file = ["dep:tokio", "dep:futures"]
reqwest = ["dep:reqwest"]
redis = ["dep:bb8-redis"]

[dependencies]
async-trait = "0.1"
bb8-redis = { version = "0.12", optional = true }
bb8-postgres = { version = "0.8", optional = true }
bincode = "1"
bs58 = "0.4"
etag = "4"
futures = { version = "0.3", optional = true }
lipl-util = { path = "../lipl-util" }
parts = { path = "../parts" }
reqwest = { version = "0.11.13", optional = true }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
serde_with = "2.0"
thiserror = "1"
tokio = { version = "1.23", features = ["rt"], optional = true }
uuid = { version = "1.0", features = ["v4"] }
